Introduce trace flag to mark circular reference keys (#1)
sindresorhus/safe-stringify pull request #3
Opened 2022-04-23 13:37 UTC by GeorgeGkas

2022-05-06 04:11 UTC, sindresorhus commented
Can you add a test where the trace refers to a nested property?

2022-05-06 04:12 UTC, sindresorhus requested changes

2022-05-06 04:12 UTC, sindresorhus commented on readme.md
> +//=> '{ "a": true, "b": "[Circular *]" }'
I think the example should be moved to the `trace` option docs.

2022-05-06 04:12 UTC, sindresorhus commented on readme.md
> +//=> '{ "a": true, "b": "[Circular *]" }'
```suggestion
//=> '{"a":true,"b":"[Circular *]"}'
```

2022-05-06 04:12 UTC, sindresorhus commented on readme.md
> +//=> '{ "a": true, "b": "[Circular *]" }'
It would be better to use an example that shows a named pointer `*c`.

2022-05-06 04:12 UTC, sindresorhus commented on readme.md
> +Type: `boolean`
```suggestion
Type: `boolean`\
Default: `false`
```

2022-05-06 04:12 UTC, sindresorhus commented on index.d.ts
> +	 By default, this option is set to false.
Use the default notation: https://github.com/sindresorhus/typescript-definition-style-guide#documentation

2022-05-06 04:12 UTC, sindresorhus commented on index.d.ts
> +	 Enable key tracing for circular references.
Incorrect indentation.

2022-05-06 04:12 UTC, sindresorhus commented on readme.md
> +Enable key tracing for circular references.
I think the description should be clearer about what it does.

2022-07-07 11:07 UTC, sindresorhus commented
@GeorgeGkas Still interested in finishing this? :)

2022-07-07 11:45 UTC, GeorgeGkas commented
Hey @sindresorhus. I'm looking into this a bit more and I believe we still have not covered all the cases. The current implementation has a bug. Consider the following example:

```js
const foo = {a: true};
foo.b = {};
foo.c = foo.b;
```

If we run `safeStringify` we get the following result:

```json
{
        "a": true,
        "b": {},
        "c": "[Circular *b]"
}
```

where the correct output should be:

```json
{
        "a": true,
        "b": {},
        "c": {}
}
```

Even if there is no circular dependency, the algorithm thinks otherwise. This results from the way we check for circular dependencies. Unfortunately, I don't have time to look into this in more depth now. Should I close this PR and come back again with a better

2022-07-21 16:02 UTC, sindresorhus commented
I'm aware of that issue and intend to look into it, but I think that issue needs to block this pull request.

2023-03-19 16:31 UTC, sindresorhus commented
Closing for lack of activity.

2023-03-19 16:31 UTC, closed without merging